# Generated by Django 6.0 on 2025-12-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='placed', help_text='Current status of the order', max_length=20),
        ),
    ]
