# Generated by Django 6.0 on 2025-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, default='Skopje', help_text='Delivery address snapshot captured at checkout.', max_length=255),
        ),
    ]
